name: Stock Check
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  check_stock:
    runs-on: ubuntu-latest
    name: Check Stock

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run Script
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          pip install requests beautifulsoup4
          python main.py
